// PitchLens — Match Memory Data
// Six World Cup 2022 Group Stage matches

export type RawEvent = {
  minute: number;
  second: number;
  event_type: "foul" | "goal" | "substitution" | "Yellow Card";
  team: string;
  player?: string;
  player_out?: string;
  player_in?: string;
};

export type TeamMeta = {
  name: string;
  code: string;
  flag: string;          // emoji flag (fallback)
  flagCode: string;      // ISO 3166-1 alpha-2 for flagcdn.com
  color: string;         // primary kit / accent
  colorDim: string;      // rgba for pitch dots
  side: "home" | "away";
};

export type MatchMeta = {
  id: string;
  home: TeamMeta;
  away: TeamMeta;
  stage: string;
  venue: string;
  date: string;
  headline: string;
  subline: string;
  score: [number, number]; // [home goals, away goals] — final
};

// ─── TEAM REGISTRY ────────────────────────────────────────────────
export const TEAM_REGISTRY: Record<string, Omit<TeamMeta, "side">> = {
  "Germany":       { name: "Germany",       code: "GER", flag: "🇩🇪", flagCode: "de", color: "#d9d9d9", colorDim: "rgba(217,217,217,0.85)" },
  "Japan":         { name: "Japan",         code: "JPN", flag: "🇯🇵", flagCode: "jp", color: "#003f87", colorDim: "rgba(0,63,135,0.85)"   },
  "Spain":         { name: "Spain",         code: "ESP", flag: "🇪🇸", flagCode: "es", color: "#c60b1e", colorDim: "rgba(198,11,30,0.85)"  },
  "Ghana":         { name: "Ghana",         code: "GHA", flag: "🇬🇭", flagCode: "gh", color: "#006b3f", colorDim: "rgba(0,107,63,0.85)"   },
  "Portugal":      { name: "Portugal",      code: "POR", flag: "🇵🇹", flagCode: "pt", color: "#006600", colorDim: "rgba(0,102,0,0.85)"    },
  "Belgium":       { name: "Belgium",       code: "BEL", flag: "🇧🇪", flagCode: "be", color: "#c8102e", colorDim: "rgba(200,16,46,0.85)"  },
  "Croatia":       { name: "Croatia",       code: "CRO", flag: "🇭🇷", flagCode: "hr", color: "#ff0000", colorDim: "rgba(255,0,0,0.85)"    },
  "England":       { name: "England",       code: "ENG", flag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿", flagCode: "gb-eng", color: "#ffffff", colorDim: "rgba(255,255,255,0.85)" },
  "Wales":         { name: "Wales",         code: "WAL", flag: "🏴󠁧󠁢󠁷󠁬󠁳󠁿", flagCode: "gb-wls", color: "#c8102e", colorDim: "rgba(200,16,46,0.85)"  },
  "Iran":          { name: "Iran",          code: "IRN", flag: "🇮🇷", flagCode: "ir", color: "#239f40", colorDim: "rgba(35,159,64,0.85)"  },
  "United States": { name: "United States", code: "USA", flag: "🇺🇸", flagCode: "us", color: "#b22234", colorDim: "rgba(178,34,52,0.85)"  },
};

// ─── MATCH REGISTRY ───────────────────────────────────────────────
export const MATCH_META: Record<string, MatchMeta> = {
  "germany-japan": {
    id: "germany-japan",
    home: { ...TEAM_REGISTRY["Germany"], side: "home" },
    away: { ...TEAM_REGISTRY["Japan"],   side: "away" },
    stage: "Group Stage · Group E",
    venue: "Khalifa International Stadium",
    date: "23 Nov 2022",
    headline: "The Giant Killers",
    subline: "Japan overturns history with two second-half goals to stun Germany.",
    score: [1, 2],
  },
  "iran-usa": {
    id: "iran-usa",
    home: { ...TEAM_REGISTRY["Iran"],          side: "home" },
    away: { ...TEAM_REGISTRY["United States"], side: "away" },
    stage: "Group Stage · Group B",
    venue: "Al Thumama Stadium",
    date: "29 Nov 2022",
    headline: "The Rivalry Renewed",
    subline: "Pulisic scores at personal cost to send the USA through.",
    score: [0, 1],
  },
  "england-wales": {
    id: "england-wales",
    home: { ...TEAM_REGISTRY["England"], side: "home" },
    away: { ...TEAM_REGISTRY["Wales"],   side: "away" },
    stage: "Group Stage · Group B",
    venue: "Ahmad Bin Ali Stadium",
    date: "29 Nov 2022",
    headline: "The Home Nations Derby",
    subline: "Rashford's double and Foden's precision end Wales's World Cup.",
    score: [3, 0],
  },
  "ghana-portugal": {
    id: "ghana-portugal",
    home: { ...TEAM_REGISTRY["Ghana"],    side: "home" },
    away: { ...TEAM_REGISTRY["Portugal"], side: "away" },
    stage: "Group Stage · Group H",
    venue: "Stadium 974",
    date: "24 Nov 2022",
    headline: "Five Goals. No Dull Moments.",
    subline: "Ronaldo, Joao Felix, and Leao hand Portugal victory in a high-drama thriller.",
    score: [2, 3],
  },
  "japan-spain": {
    id: "japan-spain",
    home: { ...TEAM_REGISTRY["Japan"], side: "home" as const },
    away: { ...TEAM_REGISTRY["Spain"], side: "away" as const },
    stage: "Group Stage · Group E",
    venue: "Khalifa International Stadium",
    date: "1 Dec 2022",
    headline: "Japan Stun Spain Too",
    subline: "Japan come from behind — Doan and Tanaka complete a historic double upset.",
    score: [2, 1],
  },
  "belgium-croatia": {
    id: "belgium-croatia",
    home: { ...TEAM_REGISTRY["Belgium"], side: "home" },
    away: { ...TEAM_REGISTRY["Croatia"], side: "away" },
    stage: "Group Stage · Group F",
    venue: "Ahmad Bin Ali Stadium",
    date: "1 Dec 2022",
    headline: "The Golden Generation Falls",
    subline: "Belgium's golden generation ends not with a bang, but a goalless draw.",
    score: [0, 0],
  },
};

// ─── MATCH RAW EVENT DATA ─────────────────────────────────────────

export const GERMANY_JAPAN: RawEvent[] = [
  { minute:18, second:5,  event_type:"foul",         team:"Japan",   player:"Takefusa Kubo" },
  { minute:18, second:36, event_type:"foul",         team:"Germany", player:"Kai Havertz" },
  { minute:29, second:19, event_type:"foul",         team:"Japan",   player:"Takefusa Kubo" },
  { minute:30, second:43, event_type:"foul",         team:"Japan",   player:"Shūichi Gonda" },
  { minute:32, second:35, event_type:"goal",         team:"Germany", player:"İlkay Gündoğan" },
  { minute:33, second:53, event_type:"foul",         team:"Germany", player:"Kai Havertz" },
  { minute:35, second:42, event_type:"foul",         team:"Germany", player:"Nico Schlotterbeck" },
  { minute:41, second:44, event_type:"foul",         team:"Japan",   player:"Wataru Endo" },
  { minute:45, second:3,  event_type:"foul",         team:"Germany", player:"David Raum" },
  { minute:45, second:0,  event_type:"substitution", team:"Japan",   player_out:"Takefusa Kubo",     player_in:"Takehiro Tomiyasu" },
  { minute:45, second:52, event_type:"foul",         team:"Japan",   player:"Ko Itakura" },
  { minute:47, second:49, event_type:"foul",         team:"Germany", player:"İlkay Gündoğan" },
  { minute:48, second:18, event_type:"foul",         team:"Japan",   player:"Daizen Maeda" },
  { minute:50, second:31, event_type:"foul",         team:"Japan",   player:"Maya Yoshida" },
  { minute:55, second:55, event_type:"foul",         team:"Japan",   player:"Ko Itakura" },
  { minute:56, second:33, event_type:"substitution", team:"Japan",   player_out:"Yuto Nagatomo",     player_in:"Kaoru Mitoma" },
  { minute:56, second:39, event_type:"substitution", team:"Japan",   player_out:"Daizen Maeda",      player_in:"Takuma Asano" },
  { minute:57, second:38, event_type:"foul",         team:"Japan",   player:"Hiroki Sakai" },
  { minute:61, second:34, event_type:"foul",         team:"Japan",   player:"Ko Itakura" },
  { minute:63, second:14, event_type:"foul",         team:"Japan",   player:"Takuma Asano" },
  { minute:66, second:37, event_type:"substitution", team:"Germany", player_out:"Thomas Müller",     player_in:"Jonas Hofmann" },
  { minute:67, second:5,  event_type:"substitution", team:"Germany", player_out:"İlkay Gündoğan",   player_in:"Leon Goretzka" },
  { minute:70, second:38, event_type:"substitution", team:"Japan",   player_out:"Ao Tanaka",         player_in:"Ritsu Doan" },
  { minute:71, second:55, event_type:"foul",         team:"Germany", player:"Leon Goretzka" },
  { minute:73, second:53, event_type:"substitution", team:"Japan",   player_out:"Hiroki Sakai",      player_in:"Takumi Minamino" },
  { minute:74, second:46, event_type:"goal",         team:"Japan",   player:"Ritsu Doan" },
  { minute:78, second:13, event_type:"substitution", team:"Germany", player_out:"Jamal Musiala",     player_in:"Mario Götze" },
  { minute:78, second:14, event_type:"substitution", team:"Germany", player_out:"Kai Havertz",       player_in:"Niclas Füllkrug" },
  { minute:82, second:7,  event_type:"foul",         team:"Germany", player:"Nico Schlotterbeck" },
  { minute:82, second:42, event_type:"goal",         team:"Japan",   player:"Takuma Asano" },
  { minute:84, second:8,  event_type:"foul",         team:"Japan",   player:"Wataru Endo" },
  { minute:87, second:56, event_type:"foul",         team:"Japan",   player:"Wataru Endo" },
  { minute:89, second:1,  event_type:"substitution", team:"Germany", player_out:"Serge Gnabry",      player_in:"Youssoufa Moukoko" },
  { minute:94, second:21, event_type:"foul",         team:"Japan",   player:"Takuma Asano" },
  { minute:96, second:13, event_type:"foul",         team:"Japan",   player:"Takumi Minamino" },
];

export const IRAN_USA: RawEvent[] = [
  { minute:0,  second:7,  event_type:"foul",         team:"United States", player:"Weston McKennie" },
  { minute:8,  second:3,  event_type:"foul",         team:"Iran",          player:"Ramin Rezaeian" },
  { minute:9,  second:23, event_type:"foul",         team:"Iran",          player:"Ehsan Hajsafi" },
  { minute:19, second:13, event_type:"foul",         team:"Iran",          player:"Mehdi Taremi" },
  { minute:26, second:47, event_type:"foul",         team:"Iran",          player:"Ramin Rezaeian" },
  { minute:33, second:23, event_type:"foul",         team:"Iran",          player:"Sardar Azmoun" },
  { minute:33, second:29, event_type:"foul",         team:"United States", player:"Antonee Robinson" },
  { minute:37, second:49, event_type:"goal",         team:"United States", player:"Christian Pulisic" },
  { minute:41, second:47, event_type:"foul",         team:"Iran",          player:"Ramin Rezaeian" },
  { minute:42, second:18, event_type:"foul",         team:"United States", player:"Tyler Adams" },
  { minute:43, second:39, event_type:"foul",         team:"United States", player:"Yunus Dimoara Musah" },
  { minute:47, second:1,  event_type:"substitution", team:"Iran",          player_out:"Milad Mohammadi",  player_in:"Ali Karimi" },
  { minute:48, second:43, event_type:"foul",         team:"Iran",          player:"Sardar Azmoun" },
  { minute:50, second:7,  event_type:"foul",         team:"Iran",          player:"Ali Gholizadeh" },
  { minute:45, second:0,  event_type:"substitution", team:"United States", player_out:"Christian Pulisic", player_in:"Brenden Aaronson" },
  { minute:45, second:0,  event_type:"substitution", team:"Iran",          player_out:"Sardar Azmoun",    player_in:"Saman Ghoddos" },
  { minute:45, second:22, event_type:"foul",         team:"United States", player:"Joshua Sargent" },
  { minute:46, second:22, event_type:"foul",         team:"Iran",          player:"Seyed Majid Hosseini" },
  { minute:48, second:55, event_type:"foul",         team:"Iran",          player:"Saman Ghoddos" },
  { minute:53, second:29, event_type:"foul",         team:"Iran",          player:"Ali Karimi" },
  { minute:53, second:53, event_type:"foul",         team:"Iran",          player:"Mehdi Taremi" },
  { minute:59, second:20, event_type:"foul",         team:"Iran",          player:"Saeid Ezatolahi Afagh" },
  { minute:60, second:34, event_type:"foul",         team:"United States", player:"Weston McKennie" },
  { minute:60, second:52, event_type:"foul",         team:"United States", player:"Tyler Adams" },
  { minute:62, second:23, event_type:"foul",         team:"Iran",          player:"Ali Karimi" },
  { minute:63, second:47, event_type:"foul",         team:"United States", player:"Joshua Sargent" },
  { minute:64, second:6,  event_type:"foul",         team:"Iran",          player:"Mehdi Taremi" },
  { minute:64, second:48, event_type:"substitution", team:"United States", player_out:"Weston McKennie", player_in:"Kellyn Kai Perry-Acosta" },
  { minute:66, second:27, event_type:"foul",         team:"Iran",          player:"Morteza Pouraliganji" },
  { minute:66, second:57, event_type:"foul",         team:"Iran",          player:"Ramin Rezaeian" },
  { minute:70, second:36, event_type:"substitution", team:"Iran",          player_out:"Ahmad Nourollahi", player_in:"Mehdi Torabi" },
  { minute:71, second:3,  event_type:"substitution", team:"Iran",          player_out:"Ehsan Hajsafi",    player_in:"Abolfazl Jalali" },
  { minute:76, second:14, event_type:"foul",         team:"Iran",          player:"Seyed Majid Hosseini" },
  { minute:76, second:55, event_type:"substitution", team:"United States", player_out:"Joshua Sargent",   player_in:"Haji Wright" },
  { minute:76, second:56, event_type:"substitution", team:"Iran",          player_out:"Ali Gholizadeh",   player_in:"Karim Ansarifard" },
  { minute:77, second:41, event_type:"foul",         team:"United States", player:"Yunus Dimoara Musah" },
  { minute:80, second:10, event_type:"foul",         team:"United States", player:"Timothy Weah" },
  { minute:81, second:8,  event_type:"substitution", team:"United States", player_out:"Timothy Weah",     player_in:"Walker Zimmerman" },
  { minute:81, second:9,  event_type:"substitution", team:"United States", player_out:"Sergino Dest",     player_in:"Shaquell Moore" },
  { minute:81, second:49, event_type:"foul",         team:"United States", player:"Yunus Dimoara Musah" },
  { minute:82, second:27, event_type:"Yellow Card",  team:"Iran",          player:"Mohammad Hossein Kanani Zadegan" },
  { minute:84, second:39, event_type:"foul",         team:"Iran",          player:"Saman Ghoddos" },
  { minute:89, second:2,  event_type:"foul",         team:"Iran",          player:"Ali Karimi" },
  { minute:91, second:43, event_type:"foul",         team:"United States", player:"Yunus Dimoara Musah" },
  { minute:95, second:26, event_type:"foul",         team:"Iran",          player:"Abolfazl Jalali" },
  { minute:97, second:18, event_type:"foul",         team:"United States", player:"Haji Wright" },
];

export const ENGLAND_WALES: RawEvent[] = [
  { minute:5,  second:18, event_type:"foul",         team:"England", player:"Jordan Brian Henderson" },
  { minute:6,  second:31, event_type:"foul",         team:"England", player:"Declan Rice" },
  { minute:13, second:1,  event_type:"foul",         team:"Wales",   player:"Neco Williams" },
  { minute:16, second:24, event_type:"foul",         team:"Wales",   player:"Chris Mepham" },
  { minute:20, second:15, event_type:"foul",         team:"Wales",   player:"Kieffer Roberto Francisco Moore" },
  { minute:21, second:0,  event_type:"foul",         team:"Wales",   player:"Neco Williams" },
  { minute:22, second:11, event_type:"foul",         team:"Wales",   player:"Ben Davies" },
  { minute:26, second:36, event_type:"foul",         team:"England", player:"Phil Foden" },
  { minute:27, second:54, event_type:"foul",         team:"Wales",   player:"Joe Allen" },
  { minute:28, second:4,  event_type:"foul",         team:"England", player:"Jordan Brian Henderson" },
  { minute:28, second:39, event_type:"foul",         team:"Wales",   player:"Daniel James" },
  { minute:35, second:56, event_type:"substitution", team:"Wales",   player_out:"Neco Williams",               player_in:"Connor Roberts" },
  { minute:36, second:12, event_type:"foul",         team:"England", player:"Harry Maguire" },
  { minute:43, second:10, event_type:"foul",         team:"Wales",   player:"Aaron Ramsey" },
  { minute:45, second:45, event_type:"foul",         team:"England", player:"Kyle Walker" },
  { minute:45, second:0,  event_type:"substitution", team:"Wales",   player_out:"Gareth Frank Bale",            player_in:"Brennan Johnson" },
  { minute:46, second:34, event_type:"foul",         team:"Wales",   player:"Brennan Johnson" },
  { minute:47, second:56, event_type:"foul",         team:"Wales",   player:"Joe Rodon" },
  { minute:49, second:17, event_type:"goal",         team:"England", player:"Marcus Rashford" },
  { minute:50, second:53, event_type:"goal",         team:"England", player:"Phil Foden" },
  { minute:52, second:33, event_type:"foul",         team:"Wales",   player:"Aaron Ramsey" },
  { minute:53, second:16, event_type:"foul",         team:"England", player:"Jordan Brian Henderson" },
  { minute:56, second:24, event_type:"foul",         team:"Wales",   player:"Brennan Johnson" },
  { minute:56, second:50, event_type:"substitution", team:"England", player_out:"Kyle Walker",                  player_in:"Trent Alexander-Arnold" },
  { minute:57, second:6,  event_type:"substitution", team:"England", player_out:"Harry Kane",                   player_in:"Callum Wilson" },
  { minute:57, second:13, event_type:"substitution", team:"England", player_out:"Declan Rice",                  player_in:"Kalvin Phillips" },
  { minute:58, second:37, event_type:"substitution", team:"Wales",   player_out:"Ben Davies",                   player_in:"Joseff Morrell" },
  { minute:60, second:34, event_type:"foul",         team:"Wales",   player:"Aaron Ramsey" },
  { minute:64, second:50, event_type:"substitution", team:"England", player_out:"Luke Shaw",                    player_in:"Kieran Trippier" },
  { minute:67, second:40, event_type:"goal",         team:"England", player:"Marcus Rashford" },
  { minute:72, second:19, event_type:"foul",         team:"England", player:"Phil Foden" },
  { minute:75, second:1,  event_type:"substitution", team:"England", player_out:"Marcus Rashford",              player_in:"Jack Grealish" },
  { minute:75, second:39, event_type:"foul",         team:"Wales",   player:"Joseff Morrell" },
  { minute:76, second:0,  event_type:"foul",         team:"England", player:"Trent Alexander-Arnold" },
  { minute:76, second:15, event_type:"substitution", team:"Wales",   player_out:"Daniel James",                 player_in:"Harry Wilson" },
  { minute:78, second:29, event_type:"foul",         team:"England", player:"Kalvin Phillips" },
  { minute:80, second:20, event_type:"substitution", team:"Wales",   player_out:"Joe Allen",                    player_in:"Rubin Colwill" },
  { minute:82, second:1,  event_type:"foul",         team:"England", player:"Harry Maguire" },
  { minute:86, second:54, event_type:"foul",         team:"Wales",   player:"Chris Mepham" },
  { minute:87, second:36, event_type:"foul",         team:"Wales",   player:"Ethan Ampadu" },
  { minute:88, second:0,  event_type:"foul",         team:"Wales",   player:"Kieffer Roberto Francisco Moore" },
  { minute:89, second:2,  event_type:"foul",         team:"Wales",   player:"Ethan Ampadu" },
  { minute:91, second:33, event_type:"foul",         team:"Wales",   player:"Chris Mepham" },
];

export const GHANA_PORTUGAL: RawEvent[] = [
  { minute:1,  second:28, event_type:"foul",         team:"Portugal", player:"Cristiano Ronaldo dos Santos Aveiro" },
  { minute:2,  second:37, event_type:"foul",         team:"Ghana",    player:"Abdul Rahman Baba" },
  { minute:10, second:46, event_type:"foul",         team:"Ghana",    player:"Thomas Teye Partey" },
  { minute:14, second:29, event_type:"foul",         team:"Portugal", player:"Rúben Diogo Da Silva Neves" },
  { minute:19, second:17, event_type:"foul",         team:"Ghana",    player:"Alidu Seidu" },
  { minute:23, second:39, event_type:"foul",         team:"Portugal", player:"Rúben Diogo Da Silva Neves" },
  { minute:24, second:51, event_type:"foul",         team:"Portugal", player:"João Félix Sequeira" },
  { minute:26, second:3,  event_type:"foul",         team:"Ghana",    player:"Alexander Djiku" },
  { minute:26, second:30, event_type:"foul",         team:"Ghana",    player:"Iñaki Williams Arthuer" },
  { minute:29, second:3,  event_type:"foul",         team:"Ghana",    player:"Salis Abdul Samed" },
  { minute:30, second:26, event_type:"foul",         team:"Portugal", player:"Cristiano Ronaldo dos Santos Aveiro" },
  { minute:31, second:14, event_type:"foul",         team:"Ghana",    player:"Daniel Amartey" },
  { minute:31, second:42, event_type:"foul",         team:"Ghana",    player:"Abdul Rahman Baba" },
  { minute:33, second:35, event_type:"foul",         team:"Ghana",    player:"André Ayew Pelé" },
  { minute:37, second:38, event_type:"foul",         team:"Ghana",    player:"Mohamed Salisu" },
  { minute:41, second:36, event_type:"foul",         team:"Portugal", player:"João Félix Sequeira" },
  { minute:42, second:35, event_type:"foul",         team:"Ghana",    player:"Mohamed Salisu" },
  { minute:43, second:12, event_type:"foul",         team:"Portugal", player:"Otávio Edmilson da Silva Monteiro" },
  { minute:44, second:55, event_type:"foul",         team:"Ghana",    player:"Mohammed Kudus" },
  { minute:45, second:46, event_type:"foul",         team:"Portugal", player:"João Félix Sequeira" },
  { minute:47, second:43, event_type:"foul",         team:"Portugal", player:"Otávio Edmilson da Silva Monteiro" },
  { minute:48, second:14, event_type:"foul",         team:"Ghana",    player:"André Ayew Pelé" },
  { minute:50, second:35, event_type:"foul",         team:"Portugal", player:"Bernardo Mota Veiga de Carvalho e Silva" },
  { minute:51, second:6,  event_type:"foul",         team:"Ghana",    player:"Abdul Rahman Baba" },
  { minute:51, second:26, event_type:"foul",         team:"Ghana",    player:"Alidu Seidu" },
  { minute:53, second:40, event_type:"foul",         team:"Portugal", player:"Otávio Edmilson da Silva Monteiro" },
  { minute:55, second:49, event_type:"substitution", team:"Portugal", player_out:"Otávio Edmilson da Silva Monteiro", player_in:"William Silva de Carvalho" },
  { minute:56, second:40, event_type:"foul",         team:"Ghana",    player:"Alidu Seidu" },
  { minute:60, second:24, event_type:"foul",         team:"Portugal", player:"Rúben Santos Gato Alves Dias" },
  { minute:61, second:55, event_type:"foul",         team:"Ghana",    player:"Mohamed Salisu" },
  { minute:64, second:20, event_type:"goal",         team:"Portugal", player:"Cristiano Ronaldo dos Santos Aveiro" },
  { minute:65, second:40, event_type:"substitution", team:"Ghana",    player_out:"Alidu Seidu",          player_in:"Tariq Lamptey" },
  { minute:69, second:31, event_type:"foul",         team:"Ghana",    player:"Tariq Lamptey" },
  { minute:72, second:11, event_type:"goal",         team:"Ghana",    player:"André Ayew Pelé" },
  { minute:75, second:40, event_type:"substitution", team:"Ghana",    player_out:"Mohammed Kudus",       player_in:"Osman Bukari" },
  { minute:76, second:22, event_type:"substitution", team:"Ghana",    player_out:"André Ayew Pelé",      player_in:"Jordan Ayew" },
  { minute:76, second:46, event_type:"substitution", team:"Portugal", player_out:"Rúben Diogo Da Silva Neves", player_in:"Rafael Alexandre Conceição Leão" },
  { minute:77, second:6,  event_type:"goal",         team:"Portugal", player:"João Félix Sequeira" },
  { minute:79, second:21, event_type:"goal",         team:"Portugal", player:"Rafael Alexandre Conceição Leão" },
  { minute:81, second:43, event_type:"foul",         team:"Portugal", player:"Rafael Alexandre Conceição Leão" },
  { minute:87, second:18, event_type:"substitution", team:"Portugal", player_out:"Cristiano Ronaldo dos Santos Aveiro", player_in:"Gonçalo Matias Ramos" },
  { minute:87, second:23, event_type:"substitution", team:"Portugal", player_out:"João Félix Sequeira",  player_in:"João Mário Naval da Costa Eduardo" },
  { minute:88, second:28, event_type:"goal",         team:"Ghana",    player:"Osman Bukari" },
  { minute:89, second:30, event_type:"foul",         team:"Portugal", player:"Danilo Luís Hélio Pereira" },
  { minute:90, second:29, event_type:"Yellow Card",  team:"Ghana",    player:"Iñaki Williams Arthuer" },
  { minute:93, second:18, event_type:"foul",         team:"Ghana",    player:"Osman Bukari" },
  { minute:94, second:28, event_type:"foul",         team:"Portugal", player:"Bruno Miguel Borges Fernandes" },
  { minute:96, second:35, event_type:"foul",         team:"Ghana",    player:"Daniel Amartey" },
];

export const BELGIUM_CROATIA: RawEvent[] = [
  { minute:6,  second:33, event_type:"foul",         team:"Belgium", player:"Axel Witsel" },
  { minute:8,  second:15, event_type:"foul",         team:"Croatia", player:"Joško Gvardiol" },
  { minute:9,  second:13, event_type:"foul",         team:"Croatia", player:"Marko Livaja" },
  { minute:13, second:48, event_type:"foul",         team:"Belgium", player:"Axel Witsel" },
  { minute:29, second:22, event_type:"foul",         team:"Croatia", player:"Ivan Perišić" },
  { minute:31, second:8,  event_type:"foul",         team:"Belgium", player:"Axel Witsel" },
  { minute:34, second:30, event_type:"foul",         team:"Croatia", player:"Marcelo Brozović" },
  { minute:35, second:19, event_type:"foul",         team:"Croatia", player:"Marko Livaja" },
  { minute:38, second:17, event_type:"foul",         team:"Belgium", player:"Axel Witsel" },
  { minute:41, second:21, event_type:"foul",         team:"Croatia", player:"Marko Livaja" },
  { minute:43, second:24, event_type:"foul",         team:"Croatia", player:"Luka Modrić" },
  { minute:47, second:34, event_type:"foul",         team:"Belgium", player:"Leander Dendoncker" },
  { minute:45, second:0,  event_type:"substitution", team:"Belgium", player_out:"Dries Mertens",           player_in:"Romelu Lukaku Menama" },
  { minute:54, second:28, event_type:"foul",         team:"Croatia", player:"Marko Livaja" },
  { minute:58, second:5,  event_type:"substitution", team:"Belgium", player_out:"Leandro Trossard",        player_in:"Thorgan Hazard" },
  { minute:60, second:37, event_type:"foul",         team:"Belgium", player:"Romelu Lukaku Menama" },
  { minute:63, second:16, event_type:"substitution", team:"Croatia", player_out:"Marko Livaja",            player_in:"Bruno Petković" },
  { minute:63, second:42, event_type:"substitution", team:"Croatia", player_out:"Andrej Kramarić",         player_in:"Mario Pašalić" },
  { minute:65, second:56, event_type:"foul",         team:"Belgium", player:"Leander Dendoncker" },
  { minute:67, second:45, event_type:"foul",         team:"Croatia", player:"Joško Gvardiol" },
  { minute:69, second:22, event_type:"foul",         team:"Croatia", player:"Marcelo Brozović" },
  { minute:71, second:30, event_type:"substitution", team:"Belgium", player_out:"Yannick Ferreira Carrasco", player_in:"Jeremy Doku" },
  { minute:71, second:37, event_type:"substitution", team:"Belgium", player_out:"Leander Dendoncker",       player_in:"Youri Tielemans" },
  { minute:74, second:25, event_type:"foul",         team:"Belgium", player:"Youri Tielemans" },
  { minute:83, second:49, event_type:"foul",         team:"Belgium", player:"Timothy Castagne" },
  { minute:86, second:37, event_type:"substitution", team:"Belgium", player_out:"Thomas Meunier",          player_in:"Eden Hazard" },
  { minute:87, second:49, event_type:"foul",         team:"Croatia", player:"Mario Pašalić" },
  { minute:90, second:54, event_type:"substitution", team:"Croatia", player_out:"Mateo Kovačić",           player_in:"Lovro Majer" },
  { minute:92, second:2,  event_type:"foul",         team:"Belgium", player:"Youri Tielemans" },
];

export const JAPAN_SPAIN: RawEvent[] = [
  { minute:6,  second:34, event_type:"foul",         team:"Spain",  player:"Pau Francisco Torres" },
  { minute:10, second:26, event_type:"foul",         team:"Japan",  player:"Daichi Kamada" },
  { minute:11, second:0,  event_type:"goal",         team:"Spain",  player:"Álvaro Borja Morata Martín" },
  { minute:17, second:50, event_type:"foul",         team:"Spain",  player:"Daniel Olmo Carvajal" },
  { minute:19, second:48, event_type:"foul",         team:"Japan",  player:"Shogo Taniguchi" },
  { minute:27, second:6,  event_type:"foul",         team:"Japan",  player:"Hidemasa Morita" },
  { minute:29, second:57, event_type:"foul",         team:"Spain",  player:"Alejandro Balde Martínez" },
  { minute:31, second:24, event_type:"foul",         team:"Japan",  player:"Daizen Maeda" },
  { minute:32, second:27, event_type:"foul",         team:"Japan",  player:"Shogo Taniguchi" },
  { minute:38, second:24, event_type:"foul",         team:"Japan",  player:"Ko Itakura" },
  { minute:43, second:31, event_type:"foul",         team:"Japan",  player:"Shogo Taniguchi" },
  { minute:44, second:20, event_type:"foul",         team:"Japan",  player:"Maya Yoshida" },
  { minute:45, second:0,  event_type:"substitution", team:"Japan",  player_out:"Takefusa Kubo",         player_in:"Ritsu Doan" },
  { minute:45, second:0,  event_type:"substitution", team:"Spain",  player_out:"César Azpilicueta Tanco", player_in:"Daniel Carvajal Ramos" },
  { minute:45, second:0,  event_type:"substitution", team:"Japan",  player_out:"Yuto Nagatomo",         player_in:"Kaoru Mitoma" },
  { minute:45, second:23, event_type:"foul",         team:"Spain",  player:"Alejandro Balde Martínez" },
  { minute:47, second:48, event_type:"goal",         team:"Japan",  player:"Ritsu Doan" },
  { minute:50, second:14, event_type:"goal",         team:"Japan",  player:"Ao Tanaka" },
  { minute:54, second:0,  event_type:"foul",         team:"Spain",  player:"Rodrigo Hernández Cascante" },
  { minute:54, second:50, event_type:"foul",         team:"Spain",  player:"Rodrigo Hernández Cascante" },
  { minute:56, second:6,  event_type:"substitution", team:"Spain",  player_out:"Nicholas Williams Arthuer", player_in:"Ferrán Torres García" },
  { minute:56, second:17, event_type:"substitution", team:"Spain",  player_out:"Álvaro Borja Morata Martín", player_in:"Marco Asensio Willemsen" },
  { minute:61, second:2,  event_type:"substitution", team:"Japan",  player_out:"Daizen Maeda",           player_in:"Takuma Asano" },
  { minute:61, second:48, event_type:"foul",         team:"Japan",  player:"Ritsu Doan" },
  { minute:63, second:50, event_type:"foul",         team:"Spain",  player:"Pedro González López" },
  { minute:67, second:13, event_type:"substitution", team:"Spain",  player_out:"Pablo Martín Páez Gavira", player_in:"Anssumane Fati" },
  { minute:68, second:49, event_type:"substitution", team:"Japan",  player_out:"Daichi Kamada",           player_in:"Takehiro Tomiyasu" },
  { minute:68, second:54, event_type:"substitution", team:"Spain",  player_out:"Alejandro Balde Martínez", player_in:"Jordi Alba Ramos" },
  { minute:69, second:2,  event_type:"foul",         team:"Japan",  player:"Kaoru Mitoma" },
  { minute:81, second:38, event_type:"foul",         team:"Spain",  player:"Sergio Busquets i Burgos" },
  { minute:82, second:39, event_type:"foul",         team:"Japan",  player:"Kaoru Mitoma" },
  { minute:86, second:30, event_type:"substitution", team:"Japan",  player_out:"Ao Tanaka",               player_in:"Wataru Endo" },
];

export const ALL_MATCHES: Record<string, RawEvent[]> = {
  "germany-japan":      GERMANY_JAPAN,
  "japan-spain":        JAPAN_SPAIN,
  "iran-usa": IRAN_USA,
  "england-wales":      ENGLAND_WALES,
  "ghana-portugal":     GHANA_PORTUGAL,
  "belgium-croatia":    BELGIUM_CROATIA,
};
